### ISSUE TITLE
thresh.txt

### ISSUE THREAD

**Issue by ph09** [UcarLab/PEAS#6]
cat: thresh.txt: No such file or directory

Is this a file that I would need to provide? Or it is an issue with PEASTools.jar?

--- Getting insert size threshold. ---
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.NullPointerException
	at java.util.TreeMap.put(TreeMap.java:563)
	at org.jax.peastools.insertmetrics.PeakThreshold.getThreshold(PeakThreshold.java:85)
	at org.jax.peastools.insertmetrics.PeakThreshold.doIt(PeakThreshold.java:62)
	at org.jax.peastools.insertmetrics.PeakThreshold.main(PeakThreshold.java:36)
	at org.jax.peastools.Main.main(Main.java:34)
	... 5 more
cat: thresh.txt: No such file or directory

**Comment by ajt986** [comment]
PEASTools.jar is supposed to write the thresh.txt file. For some reason the data structure storing the chromosome writers is throwing a null pointer exception upon initialization. My best guess is that it's not reading the input chromosomes correctly. Are you providing your own chromosomes? It's also possible that the last arguments to the shell script are being incorrectly loaded as a chromosome file.
